export const DEPLOYMENT_CONST = {
    GET_DEPLOYMENT_LOADING: 'GET_DEPLOYMENT_LOADING',
    GET_DEPLOYMENT_SUCCESS: 'GET_DEPLOYMENT_SUCCESS',
    GET_DEPLOYMENT_FAILURE: 'GET_DEPLOYMENT_FAILURE',

    ADD_DEPLOYMENT_LOADING: 'ADD_DEPLOYMENT_LOADING',
    ADD_DEPLOYMENT_SUCCESS: 'ADD_DEPLOYMENT_SUCCESS',
    ADD_DEPLOYMENT_FAILURE: 'ADD_DEPLOYMENT_FAILURE',

    DELETE_DEPLOYMENT_LOADING: 'DELETE_DEPLOYMENT_LOADING',
    DELETE_DEPLOYMENT_SUCCESS: 'DELETE_DEPLOYMENT_SUCCESS',
    DELETE_DEPLOYMENT_FAILURE: 'DELETE_DEPLOYMENT_FAILURE',
}